import * as i18n from '../i18n/index.js';
// Agent Tasks(작업 현황판·새 작업·작업 상세)의 화면 문구. text/index.js 의 규율을 따른다.
//  ⚠ 원문 정본 = 설계 문서 §9(codingpt_daemon/docs/agent-tasks-design.md). 앱(codingpt_app/src/text/tasks.ts)에
//   **같은 필드명·같은 원문**의 사전이 있다 — 번역은 i18n 카탈로그(master.json → emit) 한 벌이 갖는다.
//  · 값에 문장 조립 금지. 자리표시자는 `{n}` `{name}` `{t}` `{branch}` `{base}` `{a}` `{d}` `{agent}` 뿐이다.
//  · 원문을 바꾸려면 §9 표를 먼저 고친다(§12 변경 규칙) — 여기만 바꾸면 카탈로그에 번역이 없어 한국어가 튀어나온다.

export const TASKS_TEXT = {
  ko: {
    title: "작업",
    newTask: "새 작업",
    refresh: "새로고침",
    dashboard: "작업 현황판",
    empty: "아직 작업이 없어요",
    emptyHint: "폰이나 PC 에서 프롬프트를 보내면 PC 가 별도 브랜치에서 에이전트를 실행해요",
    noHost: "연결된 PC 가 없어요",
    connectPc: "내 PC 연결",
    hostOffline: "PC 오프라인",
    pcNeedsUpdate: "이 PC 앱을 업데이트해야 작업을 만들 수 있어요",
    serverNeedsUpdate: "서버 업데이트가 필요해요",
    groupNeedsInput: "입력 대기",
    groupWorking: "작업 중",
    groupReviewReady: "리뷰 준비",
    groupIdle: "대기 중",
    groupDone: "완료",
    waitingFor: "{t} 기다리는 중",
    filesSummary: "파일 {n}개",
    commitsAhead: "커밋 {n}개",
    diffStat: "+{a} −{d}",
    noPr: "PR 없음",
    prNumber: "PR #{n}",
    prClosed: "PR 닫힘",
    prDraft: "초안",
    prMergeable: "머지 가능",
    prConflicting: "충돌",
    checksNone: "검사 없음",
    checksPending: "검사 진행 중",
    checksPassing: "검사 통과",
    checksFailing: "검사 실패",
    checkItemPending: "진행 중",
    checkItemPassing: "통과",
    checkItemFailing: "실패",
    checkItemSkipped: "건너뜀",
    answer: "답하기",
    openTerminal: "터미널 열기",
    reopenTerminal: "터미널 다시 열기",
    relaunchAgent: "에이전트 다시 실행",
    review: "리뷰",
    reopen: "다시 열기",
    resendPrompt: "프롬프트 다시 보내기",
    trustNeeded: "폴더 신뢰 확인이 필요해요",
    trustContinue: "신뢰하고 계속",
    discard: "폐기",
    discardTask: "작업 폐기",
    deleteRecord: "기록 삭제",
    detail: "상세",
    prompt: "프롬프트",
    base: "base",
    repo: "저장소",
    pc: "PC",
    agents: "에이전트",
    count: "개수",
    advanced: "고급",
    copyEnv: ".env 파일 복사",
    fetchFirst: "시작 전 fetch",
    baseDirtyHint: "{name} 에 미커밋 변경 {n}개는 포함되지 않아요",
    promptBytes: "{a} / {d} 바이트",
    start: "시작",
    cancel: "취소",
    confirm: "확인",
    notInstalled: "설치 안 됨",
    runN: "실행 {n}",
    taskOpen: "진행 중",
    taskMerged: "머지됨",
    taskClosed: "닫힘",
    taskFailed: "실패",
    stateCreating: "준비 중",
    stateLaunching: "에이전트 실행 중",
    stateRunning: "실행 중",
    stateReviewReady: "리뷰 준비",
    stateMerging: "머지 중",
    stateMerged: "머지됨",
    stateDiscarded: "폐기됨",
    stateFailed: "실패",
    opInProgress: "진행 중…",
    checking: "확인 중…",
    terminalGone: "터미널이 닫혔어요",
    agentGone: "에이전트가 실행 중이 아니에요",
    agentBusy: "에이전트가 아직 작업 중이에요",
    promptNotDelivered: "프롬프트가 전달되지 않았어요",
    keptDirty: "미커밋 변경이 있어 남겨뒀어요",
    wsNotRegistered: "PC 가 워크스페이스를 등록하지 못했어요",
    wsRemoved: "작업 워크스페이스가 정리됐어요",
    sendComments: "코멘트 에이전트에게 보내기",
    commit: "커밋",
    commitMessage: "커밋 메시지",
    skipHooks: "훅 건너뛰기(--no-verify)",
    retryCommitNoVerify: "훅 건너뛰고 다시 커밋",
    push: "푸시",
    createPr: "PR 만들기",
    prTitle: "PR 제목",
    prBody: "PR 본문",
    draftPr: "초안(draft)으로 만들기",
    merge: "머지",
    mergePr: "PR 머지",
    mergeLocal: "로컬 머지",
    mergeMethod: "머지 방식",
    methodMerge: "merge",
    methodSquash: "squash",
    methodRebase: "rebase",
    methodFf: "fast-forward",
    discardOthers: "나머지 실행 폐기",
    winner: "선택됨",
    openPr: "PR 열기",
    checkChanges: "변경 확인",
    discardConfirm: "미커밋 변경 {n}개 파일은 30일 동안 복구할 수 있게 보관한 뒤 정리해요. 폐기할까요?",
    discardUnmergedConfirm: "머지되지 않은 커밋 {n}개는 30일 동안 복구할 수 있게 보관한 뒤 정리해요. 폐기할까요?",
    discardAllConfirm: "이 작업의 모든 실행을 폐기할까요?",
    ghMissing: "GitHub CLI(gh) 가 이 PC 에 없어요",
    ghMissingHint: "터미널에서 설치한 뒤 다시 확인하세요: brew install gh",
    ghNotAuthed: "gh 로그인이 필요해요",
    ghNotAuthedHint: "PC 터미널에서 gh auth login 을 실행하거나 GH_TOKEN 환경변수를 설정하세요",
    ghError: "gh 명령이 실패했어요",
    gitMissing: "이 PC 에 git 이 없어요",
    gitCltMissing: "git 을 쓰려면 Xcode 명령줄 도구가 필요해요: xcode-select --install",
    checkAgain: "다시 확인",
    useLocalMerge: "로컬 머지로 진행",
    notGithub: "GitHub 원격이 아니라 PR 대신 로컬 머지만 할 수 있어요",
    noRemote: "원격 저장소가 없어요",
    errUncommitted: "먼저 커밋해야 해요",
    errUnmerged: "머지되지 않은 커밋이 있어요",
    errNothingToCommit: "커밋할 변경이 없어요",
    errNothingToPr: "base 에 없는 커밋이 없어요",
    errIdentity: "git 사용자 이름과 이메일을 먼저 설정하세요",
    errGitLocked: "저장소가 잠겨 있어요. 잠시 뒤 다시 시도하세요",
    errCommitHook: "커밋 훅이 실패했어요",
    errSign: "커밋 서명에 실패했어요. PC 터미널에서 한 번 커밋하거나 서명 설정을 확인하세요",
    errPushRejected: "푸시가 거부됐어요",
    errAuth: "인증에 실패했어요. PC 터미널에서 한 번 push 하거나 gh auth setup-git 을 실행하세요",
    errPrNotFound: "PR 을 찾을 수 없어요",
    errNotMergeable: "지금은 머지할 수 없어요",
    errChecksFailing: "검사가 실패한 상태예요",
    errMainDirty: "저장소에 커밋되지 않은 변경이 있어 로컬 머지를 할 수 없어요",
    errBaseMoved: "머지하는 사이 {base} 가 바뀌었어요. 다시 시도하세요",
    errConflict: "충돌이 났어요",
    conflictHint: "터미널에서 해결하거나 에이전트에게 rebase 를 지시하세요",
    errBusy: "다른 작업이 진행 중이에요",
    errInterrupted: "PC 가 재시작되어 작업이 중단됐어요",
    errTimeout: "응답이 늦어요. 잠시 뒤 상태를 다시 확인하세요",
    errTaskLimit: "동시에 실행할 수 있는 작업 수를 넘었어요",
    errTaskClosed: "이미 종료된 작업이에요",
    errBaseNotFound: "base 브랜치를 찾을 수 없어요",
    errNotRepo: "git 저장소가 아니에요",
    errAgentMissing: "선택한 에이전트가 이 PC 에 없어요",
    errLaunch: "에이전트를 실행하지 못했어요",
    errLaunchBusy: "터미널에서 다른 명령이 실행 중이에요",
    errWorktree: "작업 폴더를 만들거나 지우지 못했어요",
    errWorktreeMissing: "작업 폴더가 사라졌어요",
    errPromptTooLarge: "프롬프트가 너무 길어요(30,000 바이트까지)",
    errTasksDisabled: "이 PC 에서는 작업 기능을 쓸 수 없어요",
    errGeneric: "실패했어요",
    taskBadge: "작업: {name}",
    backToDashboard: "현황판",
    mergedInto: "{branch} → {base}",
    promptPlaceholder: "무엇을 만들까요?",
    dictate: "받아쓰기",
  },
};

/**
 * 에러 code → 필드명(§9 ERROR_KEY). 앱 text/tasks.ts 와 **같은 객체**다(교차 테스트가 필드명 집합을 대조).
 *  없는 code 는 errGeneric. MERGE_CONFLICT 는 결과 코드(MergeResult.ok:false)지만 문구는 여기서 같이 푼다.
 */
export const ERROR_KEY = {
  BAD_PARAMS: "errGeneric",
  PROMPT_TOO_LARGE: "errPromptTooLarge",
  TASK_NOT_FOUND: "errGeneric",
  RUN_NOT_FOUND: "errGeneric",
  TASK_CLOSED: "errTaskClosed",
  TASKS_DISABLED: "errTasksDisabled",
  NOT_A_REPO: "errNotRepo",
  BASE_NOT_FOUND: "errBaseNotFound",
  BASE_MOVED: "errBaseMoved",
  TASK_LIMIT: "errTaskLimit",
  AGENT_NOT_INSTALLED: "errAgentMissing",
  GIT_MISSING: "gitMissing",
  GIT_CLT_MISSING: "gitCltMissing",
  GH_MISSING: "ghMissing",
  GH_NOT_AUTHED: "ghNotAuthed",
  GH_ERROR: "ghError",
  NOT_GITHUB: "notGithub",
  NO_REMOTE: "noRemote",
  WORKTREE_ADD_FAILED: "errWorktree",
  WORKTREE_REMOVE_FAILED: "errWorktree",
  WORKTREE_MISSING: "errWorktreeMissing",
  AGENT_LAUNCH_FAILED: "errLaunch",
  LAUNCH_BUSY: "errLaunchBusy",
  PROMPT_NOT_DELIVERED: "promptNotDelivered",
  TERMINAL_GONE: "terminalGone",
  UNCOMMITTED_CHANGES: "errUncommitted",
  UNMERGED_COMMITS: "errUnmerged",
  NOTHING_TO_COMMIT: "errNothingToCommit",
  NOTHING_TO_PR: "errNothingToPr",
  GIT_IDENTITY_MISSING: "errIdentity",
  GIT_LOCKED: "errGitLocked",
  COMMIT_HOOK_FAILED: "errCommitHook",
  GIT_SIGN_FAILED: "errSign",
  PUSH_REJECTED: "errPushRejected",
  AUTH_FAILED: "errAuth",
  PR_NOT_FOUND: "errPrNotFound",
  PR_NOT_MERGEABLE: "errNotMergeable",
  CHECKS_FAILING: "errChecksFailing",
  MAIN_DIRTY: "errMainDirty",
  AGENT_BUSY: "agentBusy",
  MERGE_CONFLICT: "errConflict",
  RUN_BUSY: "errBusy",
  OP_INTERRUPTED: "errInterrupted",
  TIMEOUT: "errTimeout",
};

/** 필드명 → 지금 언어의 문구(자리표시자 치환 포함). 모르는 필드는 원문 대신 errGeneric. */
export function tt(key, vars) {
  const src = TASKS_TEXT.ko[key];
  return i18n.t(src == null ? TASKS_TEXT.ko.errGeneric : src, vars);
}

/** 에러 code → 문구. `errBaseMoved` 처럼 자리표시자가 있으면 vars 로 채운다. */
export function errText(code, vars) {
  return tt(ERROR_KEY[String(code || "")] || "errGeneric", vars);
}
