FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY . .

RUN chmod +x /app/docker-entrypoint.sh && cp /app/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

EXPOSE 5100

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["npm", "start"]
