FROM node:18-alpine

# Python 설치 (코드 실행을 위해)
RUN apk add --no-cache python3 py3-pip

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 5100

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["npm", "run", "dev"]
